name-template: "SolarDoc v$RESOLVED_VERSION 🌌✨"
tag-template: "v$RESOLVED_VERSION"
tag-prefix: "v"
categories:
  - title: "New Features"
    labels:
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
  - title: "Other Changes"
    labels:
      - "other"
      - "maintenance"
      - "optimisation"
      - "dev-env"
  - title: "Dependency Updates"
    label:
      - "dependencies"
    collapse-after: 4
version-resolver:
  major:
    labels:
      - "breaking change"
  minor:
    labels:
      - "enhancement"
  patch:
    labels:
      - "fix"
      - "maintenance"
      - "dependencies"
      - "other"
template: |
  # {INSERT_NAME} Update
  ## v$RESOLVED_VERSION - {YEAR-MONTH-DAY}

  $CHANGES

  ## Full Details

  **Compare Changes**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

exclude-labels:
  - "release"
  - "docs"
  - "spam"
  - "invalid"
  - "skip changelog"
