services:
  frontend:
    build:
      context: .
      dockerfile: ./solardoc/frontend/Dockerfile
      args:
        VITE_PROD_BACKEND_HOST: http://152.67.66.155
        VITE_PROD_BACKEND_PORT: 3000
        PUPPETEER_SKIP_DOWNLOAD: true
    volumes:
      - ./solardoc/frontend:/home/node/app
    ports:
      - "80:80"
    environment:
      PUPPETEER_SKIP_DOWNLOAD: true
      NODE_ENV: production
    depends_on:
      - rest-api
    links:
      - rest-api
    restart: always
  rest-api:
    build:
      context: .
      dockerfile: ./solardoc/rest-api/Dockerfile
      args:
        PUPPETEER_SKIP_DOWNLOAD: true
        PERSISTENT_STORAGE_PATH: ${PERSISTENT_STORAGE_PATH}
    ports:
      - "3000:3000"
    environment:
      REDIS_ROOT_PASSWORD: ${REDIS_ROOT_PASSWORD}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: redis-db
      REDIS_PORT: 6379
      PERSISTENT_STORAGE_PATH: ${PERSISTENT_STORAGE_PATH}
      PUPPETEER_SKIP_DOWNLOAD: true
      NODE_ENV: production
    volumes:
      - rest-api-persistent-storage:${PERSISTENT_STORAGE_PATH}
    depends_on:
      redis-db:
        condition: service_healthy
    links:
      - redis-db
    restart: always
  redis-db:
    build: ./solardoc/redis-db
    ports:
      - "6379:6379"
      - "8001:8001"
    privileged: true
    volumes:
      - ./solardoc/redis-db/data:/redis/data
    environment:
      REDIS_ROOT_PASSWORD: ${REDIS_ROOT_PASSWORD}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    restart: always

volumes:
  rest-api-persistent-storage:
