name: ESLint

on:
  push:
    branches: [ "*" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "dev-sprint-*" ]
  schedule:
    - cron: '25 10 * * 2'

jobs:
  eslint:
    name: Frontend ESLint Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    strategy:
      matrix:
        package: [ frontend, rest-api, asciidoc-renderer ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 8.x.x
          run_install: true

      - name: Install dependencies & ESLint Formatter
        run: |
          cd ./solardoc/${{ matrix.package }}
          pnpm install
          pnpm install -D @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: |
          cd ./solardoc/${{ matrix.package }}
          $(pnpm bin)/eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore "--format" "@microsoft/eslint-formatter-sarif" "--output-file" "../../eslint-results.sarif"
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
